// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/cch123/go-ddd/domain/aggregate"
	"github.com/cch123/go-ddd/repo/customer"
	"github.com/cch123/go-ddd/repo/order"
)

// Injectors from wire.go:

func initApp(i int) *app {
	customerRepo := customer.NewCustomer()
	aggregateCustomer := aggregate.NewCustomerAgg(customerRepo)
	orderRepo := order.NewOrder()
	aggregateOrder := aggregate.NewOrderAgg(orderRepo)
	appApp := newApp(aggregateCustomer, aggregateOrder)
	return appApp
}
