// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Order struct {
	ent.Schema
}

func (Order) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Time("created_at"), field.Time("updated_at"), field.Int("customer_id"), field.String("addr"), field.Float("price"), field.Int32("status")}
}
func (Order) Edges() []ent.Edge {
	return nil
}
func (Order) Annotations() []schema.Annotation {
	return nil
}
